# branding.py
class KyoceraColors:
    DARK_GREY, PURPLE = "#282828", "#6D2C91"
    LIGHT_GREY = "#F2F2F2"
    STATUS_ORANGE_LIGHT, STATUS_BLUE_LIGHT, STATUS_GREEN_LIGHT, STATUS_RED_LIGHT = \
        "#FAD9C6", "#CCE5F3", "#CCEFDA", "#F5B7B1"